# -*- coding: utf-8 -*-
documentation = [
_(u"""# Using AppVeyor to manage NVDA add-ons """),
"",_(u"""## Procedure to build and attach nvda-addon files to releases on GitHub"""),
"",_(u"""This can be used to automate the building of NVDA add-ons (binaries with the .nvda-addon extension), which will be uploaded from Appveyor to GitHub, and attached to the created release."""),
"",_(u"""It works for add-ons based on the [Add-on Template](https://github.com/nvdaaddons/addontemplate)."""),
"",_(u"""### Setting AppVeyor for add-ons"""),
"",_(u"""1. Get the code of an add-on."""),
"",_(u"""Example:"""),
"",_(u"""```"""),
_(u"""git clone https://github.com/username/repo"""),
"",_(u"""git pull"""),
_(u"""```"""),
"",_(u"""2. In the root of the add-on folder (where the sconstruct file is placed), paste this [AppVeyor configuration file](https://gist.github.com/nvdaes/a486e45b98566d530688f6da9ce75f84/raw/d05b620185a58327b39da1215cf3c13c01249031/appveyor.yml) (appveyor.yml)."""),
"",_(u"""3. If you don't have it, [create a personal API access token](https://github.com/settings/tokens) and [encrypt it](https://ci.appveyor.com/tools/encrypt)."""),
"",_(u"""4. In the appveyor.yml file, replace the value provided for the secure key with your encrypted token. For instance, instead of"""),
"",_(u"""```"""),
_(u"""  auth_token:"""),
_(u"""    secure: 3yxF2EQ/wfLKNEobcRfdNL6srjXjoMdRa/LSQ7z2PJNqOL3IEyiFtlnxxHeIQskH"""),
_(u"""```"""),
"",_(u"""```"""),
_(u"""auth_token:"""),
_(u"""    secure: yourEncryptedToken"""),
_(u"""```"""),
"",_(u"""Now, you can paste your appveyor.yml file to any add-on posted on your GitHub account."""),
"",_(u"""5. [Sign in with AppVeyor](https://www.appveyor.com/)."""),
"",_(u"""6. From AppVeyor, select New Project. (If needed, choose GitHub and authorize it)."""),
"",_(u"""7. Locate the name of the repo you're interested in, move the mouse over it (for instance pressing NVDA+numpadDivide or NVDA+shift+m), and activate the \"Add\" link below."""),
"",_(u"""### Releasing"""),
"",_(u"""To post a new release of an add-on, you can create a tag and push it to GitHub:"""),
"",_(u"""Example"""),
"",_(u"""```"""),
_(u"""git tag 1.0"""),
"",_(u"""git push origin 1.0"""),
_(u"""```"""),
"",_(u"""Now, the release will be created and binary-1.0.nvda-addon will be attached on GitHub."""),
"",_(u"""## Procedure to receive notifications about commits"""),
"","",_(u"""1. Create an email address to receive notifications. For instance, you may use the [groups.io email integration](https://groups.io/static/features)."""),
"",_(u"""2. In the appveyor.yml file, add these lines:"""),
"",_(u"""```"""),
"",_(u"""notifications:"""),
_(u"""  - provider: Email"""),
_(u"""    to:"""),
_(u"""      - notificationsEmailAddress.example.com"""),
"",_(u"""```"""),
"",_(u"""Replace notificationsEmailAddress.example.com with a valid email address."""),
"",_(u"""Here is a [topic in groups.io mailing list as a real example](https://nvdaes.groups.io/g/NVDAADDONSCOMMITS/topic/build_completed/27377767)."""),
"",_(u"""## References"""),
"",_(u"""- [Appveyor.yml reference](https://www.appveyor.com/docs/appveyor-yml/)"""),
_(u"""- [Publishing artifacts to GitHub Releases | AppVeyor](https://www.appveyor.com/docs/deployment/github/#configuring-in-appveyoryml)"""),
_(u"""- [Syntax of the release name value in the deploy section of the appveyor.yml configuration file](http://help.appveyor.com/discussions/questions/9221-syntax-of-the-release-name-value-in-the-deploy-section-of-the-appveyoryml-configuration-file)"""),
_(u"""- [mesa/appveyor.yml at master · anholt/mesa](https://github.com/anholt/mesa/blob/master/appveyor.yml)"""),
_(u"""- [Discussion on the NVDA add-ons mailing list](https://nvda-addons.groups.io/g/nvda-addons/topic/6220467)"""),
"",_(u"""## Aknowledgements"""),
"",_(u"""Thanks to @abdel792, @derekriemer and @tuukao for making this possible."""),
]