# -*- coding: utf-8 -*-
documentation = [
_(u"""# Citizen and Contributor Code of Conduct"""),
"",_(u"""## 1. Purpose"""),
_(u"""A primary goal of NV Access and NVDA is to be inclusive to the largest number of contributors, with the most varied and diverse backgrounds possible. As such, we are committed to providing a friendly, safe and welcoming environment for all, regardless of gender, sexual orientation, ability, ethnicity, nationality, socioeconomic status, education, level of experience and religion (or lack thereof)."""),
_(u"""This code of conduct outlines our expectations for all those who participate in our community, as well as the consequences for unacceptable behaviour."""),
_(u"""We invite all those who participate in the NVDA community to help us create safe and positive experiences for everyone. NVDA is a user driven initiative. """),
"",_(u"""## 2. Open Source Citizenship"""),
_(u"""A supplemental goal of this Code of Conduct is to increase open source citizenship by encouraging participants to recognise and strengthen the relationships between our actions and their effects on our community. """),
_(u"""Communities mirror the societies in which they exist and positive action is essential to counteract the many forms of inequality and abuses of power that exist in society."""),
_(u"""If you see someone who is making an extra effort to ensure our community is welcoming, friendly, and encourages all participants to contribute to the fullest extent, we want to know."""),
"",_(u"""## 3. Expected Behaviour"""),
_(u"""The following behaviours are expected and requested of all community members:"""),
"",_(u"""* To participate in an authentic and active way. In doing so, you contribute to the health and longevity of this community."""),
_(u"""* To exercise consideration and respect in your speech and actions."""),
_(u"""* To attempt collaboration before conflict."""),
_(u"""* To provide helpful contributions to an issue in order to encourage its progression"""),
_(u"""* To be respectful of differing viewpoints and experiences"""),
_(u"""* To gracefully accept constructive criticism"""),
_(u"""* To respect the need to prioritise issues based on NV Access, user, and community priority"""),
_(u"""* To be aware that GitHub is a public forum and refrain from publishing personal or sensitive information (your own or others). For example, carefully consider the contents of debug logs when publishing."""),
_(u"""* To refrain from demeaning, discriminatory, or harassing behaviour and speech."""),
_(u"""* To be mindful of your surroundings and of your fellow participants. Alert NV Access staff if you notice a dangerous situation, someone in distress, or violations of this Code of Conduct, even if they seem inconsequential."""),
"",_(u"""## 4. Unacceptable Behaviour"""),
_(u"""The following behaviours are considered harassment and are unacceptable within our community:"""),
"",_(u"""* Violence, threats of violence or violent language directed against another person."""),
_(u"""* Sexist, racist, homophobic, transphobic, ableist or otherwise discriminatory jokes and language."""),
_(u"""* Posting or displaying sexually explicit or violent material."""),
_(u"""* Posting or threatening to post other people's personally identifying information (\"doxing\")."""),
_(u"""* Trolling, insulting/derogatory comments, and personal or political attacks"""),
_(u"""* Personal insults, particularly those related to gender, sexual orientation, race, religion, or disability."""),
_(u"""* Inappropriate photography or recording."""),
_(u"""* Unwelcome sexual attention. This includes sexualized comments or jokes, inappropriate touching, groping, and unwelcomed sexual advances."""),
_(u"""* Deliberate intimidation, stalking or following (online or in person)."""),
_(u"""* Advocating for, or encouraging, any of the above behaviour."""),
_(u"""* Sustained disruption of community events, including talks and presentations."""),
"",_(u"""## 5. Consequences of Unacceptable Behaviour"""),
_(u"""Unacceptable behaviour from any community member, including sponsors and those with decision-making authority, will not be tolerated."""),
_(u"""Anyone asked to stop unacceptable behaviour is expected to comply immediately."""),
_(u"""If a community member engages in unacceptable behaviour, NV Access Staff may take any action they deem appropriate, up to and including a temporary ban or permanent expulsion from the community without warning (and without refund in the case of a paid event)."""),
_(u"""NV Access Staff have the right and responsibility to remove, edit, or reject comments, commits, code, wiki edits, issues, and other contributions that are not aligned to this Code of Conduct, or to ban temporarily or permanently any contributor for other behaviours that they deem inappropriate, threatening, offensive, or harmful."""),
"",_(u"""## 6. Reporting Guidelines"""),
_(u"""If you are subject to or witness unacceptable behaviour, or have any other concerns, please notify NV Access staff as soon as possible via info@nvaccess.org. The information required for notifications includes PR/Issue Number, nature of breach, community member responsible, date and time of breach. Please note that the details of the reporter will not be disclosed, unless required to by law. """),
"",_(u"""## 7. Addressing Grievances"""),
_(u"""If you feel you have been falsely or unfairly accused of violating this Code of Conduct, you should notify NV Access at info@nvaccess.org with a concise description of your grievance. """),
"",_(u"""## 8. Scope"""),
_(u"""We expect all community participants (contributors, paid or otherwise; sponsors; and other guests) to abide by this Code of Conduct in all community venues--online and in-person--as well as in all one-on-one communications pertaining to community business."""),
_(u"""This code of conduct and its related procedures also applies to unacceptable behaviour occurring outside the scope of community activities when such behaviour has the potential to adversely affect the safety and well-being of community members. """),
_(u"""For others setting up or running an NVDA group of any kind, it is strongly recommended that a complementary Citizen and Contributor Code of Conduct is adopted. """),
"",_(u"""## 9. Contact info"""),
_(u"""info@nvaccess.org"""),
"",_(u"""## 10. License and attribution"""),
_(u"""The Citizen and Contributor Code of Conduct is distributed by NV Access Limited. """),
_(u"""Portions of text were derived from the GitHub sample Citizen and Contributor Code of Conduct, which is distributed under a Creative Commons Attribution-ShareAlike license."""),
"",_(u"""Revision1.0 adopted by NV Access Limited on 2020-09-23"""),
]