# -*- coding: utf-8 -*-
documentation = [
_(u"""[][[# Connect with the NVDA Community"""),
"",_(u"""## Official project resources"""),
"",_(u"""### Gitter Chat Room"""),
_(u"""If you would like to text chat with the developers or other NVDA users directly, other than sending -emails, you may wish to join the [NVDA chat room on Gitter](https://gitter.im/nvaccess/NVDA). It is the chat room that has been set up for discussions of all issues related to NVDA. Also, you may share tips and personal stories about using NVDA, and you may ask relevant questions after reviewing the website and product documentation, or feel free to chat about more expected features and/or bug fixes."""),
"",_(u"""If you prefer using IRC, you can also [connect to Gitter using an IRC client](https://irc.gitter.im/)."""),
"",_(u"""## Other Community Sites, Blogs and Email Lists"""),
"",_(u"""### International users' mailing List (English)"""),
"",_(u"""To join the users' list, send a blank email to: """),
_(u"""nvda+subscribe@groups.io."""),
"",_(u"""You can also visit [the homepage](https://nvda.groups.io/g/nvda) of the users' email list where you can subscribe, search and read list archives."""),
"",_(u"""### Resources for specific languages"""),
_(u"""Since the creation of NVDA, the community has created a number of independent websites, blogs and mailing lists to discuss all issues related to NVDA in their native languages. The following list shows those web resources in alphabetical order."""),
"",_(u"""Note:"""),
"",_(u"""The web resources mentioned in the following list are published independently; that's to say, they are written entirely by NVDA community around the world and thus the information/opinions expressed may not be the same as that held by the NVDA project team."""),
"",_(u""" * Arabic website: https://www.nvda-ar.org"""),
_(u"""* Arabic discussion list: https://groups.io/g/nvda-ar"""),
_(u""" * Czech/Slovak Blog: http://nvda-project.cz"""),
_(u""" * Danish website: http://www.nvda.dk"""),
_(u""" * Dutch website: https://www.nvda-nl.org"""),
_(u""" * Dutch wiki: https://wiki.nvda-nl.org"""),
_(u""" * Dutch Email List: to subscribe, send a blank email to nvdadutch+subscribe@groups.io and reply to the received message."""),
_(u""" * Finnish: http://groups.yahoo.com/group/nvda-finland"""),
_(u""" * French: http://www.nvda-fr.org"""),
_(u""" * German: https://www.facebook.com/groups/1899444343635975/?fref=nf"""),
_(u""" * German Email List: to subscribe, send a blank email to nvda-german-subscribe@ml4free.de with \"subscribe\" in the subject line."""),
_(u""" * Hungarian: http://www.nvda.hu"""),
_(u""" * Hungarian Email List: http://nvda.hu/mailman/listinfo/lista_nvda.hu"""),
_(u""" * Italian: http://www.nvda.it"""),
_(u""" * Japanese website: http://www.nvda.jp/"""),
_(u""" * Japanese mailing list: Send a blank message to nvda-japanese-users+subscribe@googlegroups.com with subscribe as the subject line."""),
_(u""" * Korean users forum on Facebook: https://www.facebook.com/groups/nvdakr"""),
_(u""" * Polish: http://www.nvda.pl"""),
_(u""" * Portuguese mailing list: to subscribe, send a blank email to nvdaemportugues+subscribe@googlegroups.com. Note that this list was formerly on Yahoo Groups."""),
_(u""" * Romanian website: http://www.nvda.ro"""),
_(u""" * Romanian mailing list: To subscribe, send an e-mail to NVDA-romanian-comunity+subscribe@googlegroups.com or you can access the link https://groups.google.com/forum/#!forum/nvda-romanian-comunity to subscribe via web."""),
_(u""" * Russian mailing list: To subscribe, send a blank email to nvda-rus-subscribe@tiflo.info and reply to the received message."""),
_(u""" * Spanish community (two different teams):"""),
_(u"""  * NVDA en español (owner: [@nvda-es](https://github.com/nvda-es))"""),
_(u"""   * Spanish website: https://nvda.es"""),
_(u"""   * Spanish mailing list: To subscribe, send a blank e-mail to nvda-es+subscribe@googlegroups.com"""),
_(u"""  * Comunidad hispanohablante de NVDA (owner: [@nvdaes](https://github.com/nvdaes))"""),
_(u"""   * Spanish website: https://nvdaes.github.io"""),
_(u"""   * Spanish mailing list: To subscribe, send a blank e-mail to lista+subscribe@nvdaes.groups.io"""),
_(u""" * Swedish mailing list: To subscribe send a blank email to nvda-request@smartlist.nu putting subscribe in the subject line."""),
_(u""" * Turkish mailing list: http://groups.yahoo.com/group/nvda_tr"""),
"",_(u""" * NVDA Simplified Chinese website: http://www.nvdacn.com"""),
_(u""" * NVDA Simplified Chinese Website is the official website of NVDA China Mainland. It provides the latest tutorials on """),
_(u"""NVDA Simplified Chinese news and plugins."""),
]