# -*- coding: utf-8 -*-
documentation = [
_(u"""# Using GitHub Actions to manage NVDA add-ons """),
"",_(u"""This document is based on the [article about Appveyor](https://github.com/nvdaaddons/nvdaaddons.github.io/wiki/appveyor)."""),
"",_(u"""## Procedure to build, test with NVDA, lint diffs and attach addon binaries to releases on GitHub"""),
"",_(u"""### Setting GitHub Actions for add-ons"""),
"",_(u"""This works for add-ons based on the [Add-on Template](https://github.com/nvdaaddons/addontemplate)."""),
"",_(u"""1. Get the code of an add-on."""),
"",_(u"""	Example:"""),
"",_(u"""	```"""),
_(u"""	git clone https://github.com/username/repo"""),
"",_(u"""	git pull"""),
_(u"""	```"""),
_(u"""2. In the root of the add-on folder (where the sconstruct file is placed), paste this [Flake8 configuration file](https://gist.githubusercontent.com/nvdaes/9caffa59ebbdcfd3e69f8a200b512be9/raw/3cbaaff48239b1b98e863901cf6a76b955412df7/setup.cfg), which uses [Flake8 rules configured for NVDA](https://raw.githubusercontent.com/nvaccess/nvda/master/tests/lint/flake8.ini). This must be named setup.cfg"""),
"",_(u"""3. In the same folder, paste this [requirements.txt file](https://raw.githubusercontent.com/nvaccess/nvda/master/tests/lint/lintInstall/requirements.txt)"""),
"",_(u"""4. In the same folder, create a file named `changelog.md`. This file should be empty or include changes for the current release."""),
"",_(u"""5. Under the root folder of the add-on repository, create a `.github/workflows` subdirectory."""),
"",_(u"""6. Inside the `repositoryRootFolder/.github/workflows` subfolder, you can include GitHub workflow files (.yml or .yaml). Feel free to use, for example, workflows available at <https://github.com/nvdaes/clipContentsDesigner/tree/master/.github/workflows>"""),
"",_(u"""Here is info about [managing workflow runs](https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs)."""),
"",_(u"""### Releasing"""),
"",_(u"""To post a new release of an add-on, you can create a tag and push it to GitHub:"""),
"",_(u"""Example"""),
"",_(u"""```"""),
_(u"""git tag 1.0"""),
"",_(u"""git push origin 1.0"""),
_(u"""```"""),
"",_(u"""Now, the release will be created and binary-1.0.nvda-addon will be attached on GitHub."""),
"",_(u"""With the provided yaml file, releases created from tags ending with \"-dev\" will be marked as prereleases."""),
"",_(u"""Example"""),
"",_(u"""```"""),
_(u"""git tag 1.0-dev"""),
"",_(u"""git push origin 1.0-dev"""),
_(u"""```"""),
"",_(u"""## References"""),
"",_(u"""### Documentation"""),
"",_(u"""- [GitHub Actions documentation](https://docs.github.com/en/free-pro-team@latest/actions)"""),
_(u"""- [Flake8 documentation](https://flake8.pycqa.org/en/latest/)"""),
"",_(u"""### Used actions"""),
"",_(u"""- [actions/checkout: action for checking out a repo](https://github.com/actions/checkout)"""),
_(u"""- [actions/upload-artifact](https://github.com/actions/upload-artifact): action for uploading artifacts"""),
_(u"""- [actions/download-artifact](https://github.com/actions/download-artifact): an action for downloading artifacts"""),
_(u"""- [unsplash/comment-on-pr@master](https://github.com/unsplash/comment-on-pr): an action to comment on a PR (may not work on Windows)"""),
_(u"""- [action/GitHubScript](https://github.com/actions/github-script): scripting GitHub API in JavaScript"""),
_(u"""- [actions/create-release: An Action to create releases via the GitHub Release API](https://github.com/actions/create-release)"""),
_(u"""- [svenstaro/upload-release-action: Upload files to a GitHub release](https://github.com/svenstaro/upload-release-action)"""),
"",_(u"""## Aknowledgements ###"""),
"",_(u"""The above workflows are created or based on work performed by @mhameed"""),
"",_(u"""<https://github.com/nvdaaddons/l10ntest>"""),
"",_(u"""Thanks also to @Josephsl and @CyrilleB79 for replies, as mentioned on this [message about GitHub workflows](https://nvda-addons.groups.io/g/nvda-addons/message/13492)"""),
]