# -*- coding: utf-8 -*-
documentation = [
_(u"""# Using GitHub webhooks to receive notifications"""),
"",_(u"""## Purpose"""),
"",_(u"""This can be helpful to receive notifications, for example on a mailing list, when Gitub repos trigger push events, i.e., when new code or tags are pushed in the add-ons development process."""),
"",_(u"""## Procedure"""),
"",_(u"""### Create a Google web app """),
"",_(u"""1. Copy this [script sample](https://gist.github.com/nvdaes/c5cb65b148e6e989d3e243b61719a80a/raw/4f5129705fa49b01ff5434535492870ac2c750e5/githubPushNotifier.gs) in an accessible editor, such as Notepadd++ or Notepad:"""),
"",_(u"""2. Replace email@example.com with the email address you want to use, for instance, using the [groups.io email integration](https://groups.io/static/features)."""),
"",_(u"""3. Create a project at"""),
_(u"""https://script.google.com"""),
"",_(u"""	- In the multi-line edit box, copy your modified script and press control+s to save."""),
_(u"""	- Select Publish > Deploy as web app."""),
_(u"""	- Under Execute the app as, select run with your account."""),
_(u"""	- Under Who has access to the app, select Anyone, even anonymous."""),
_(u"""	- Click Deploy."""),
_(u"""	- Copy the Current web app URL."""),
_(u"""	"""),
_(u"""	For more details, please see"""),
_(u"""	[Web Apps  |  Apps Script  |  Google Developers](https://developers.google.com/apps-script/guides/web)."""),
"",_(u"""### Configure a webhook on GitHub"""),
"",_(u"""1. From a GitHub repo, go to Settings > Webhooks > Add webhook."""),
_(u"""2. In the Payload URL edit box, copy the URL for your web app."""),
_(u"""3. In the Content type combo box, select application/json."""),
_(u"""4. In the Enable SSL verification set of radio buttons, disable this option."""),
_(u"""5. Press Add webhook."""),
"",_(u"""Note: In the above process, you may need to confirm your GitHub password."""),
"",_(u"""## References"""),
"",_(u"""- [Class MailApp  |  Apps Script  |  Google Developers](https://developers.google.com/apps-script/reference/mail/mail-app)"""),
_(u"""- [Webhooks | GitHub Developer Guide](https://developer.github.com/webhooks/)"""),
]