# -*- coding: utf-8 -*-
documentation = [
_(u"""# Creating PR's on the NVDA project"""),
"",_(u"""This page is meant to serve as an explanation for how to fill out [our Github pull request template](https://github.com/nvaccess/nvda/blob/master/.github/PULL_REQUEST_TEMPLATE.md)"""),
"",_(u"""## The template"""),
_(u"""At the start of the template there is a HTML comment block (starting with `<!--`), which points to this wiki page, it can be left in place and will not appear once the issue is saved. Feel free to delete it, i.e. all text up to and including `-->`."""),
"",_(u"""### Link to issue number:"""),
_(u"""Please include the issue number here, including information on how this pull request is related to it. This helps us to keep the information linked together. If this is a minor/trivial change an issue does not need to be created. If in doubt, please create one."""),
_(u"""Note that Github [allows you to automatically close issues using keywords](https://help.github.com/en/articles/closing-issues-using-keywords). For example, """),
_(u"""when writing `closes #7777` or `fixes #4242` in the body of the description, the mentioned issue will automatically be closed when the pull request is merged into the master branch. If your pull request is filed against another branch, such as beta, the particular issue will have to be close manually after merging the pull request."""),
"",_(u"""### Summary of the issue:"""),
_(u"""A quick summary of the problem you are trying to solve."""),
"",_(u"""### Description of how this pull request fixes the issue:"""),
_(u"""Please include a quick discussion of how this change addresses the issue. Please also include any links or external information you may have used in order to address the issue. This helps others to have the same background as you and learn from this work."""),
"",_(u"""### Testing performed:"""),
_(u"""Outline the steps you took to test the change. This should allow someone else to reproduce your testing."""),
"",_(u"""More broadly, try to answer the following questions:"""),
_(u"""- How have you tested to ensure that your change works as intended?"""),
_(u"""- Have you ensured testing coverage across all supported operating systems?"""),
_(u"""- Have you considered possible regressions (related features or behaviours that may break)?"""),
"",_(u"""Please use this section as an opportunity to try to convince us (and yourself) that your proposed change should be merged. """),
"",_(u"""Often in face to face development it's useful to demonstrate a change, quite often bugs are noticed at this point when the new person asks for some variation in testing approach. Since we unlikely to be able to demonstrate a feature in an interactive way, an easy to follow list of steps for a \"demo\" allows others check themselves without having to work out all the details. It also serves as a starting point for members of the community who are testing the changes that go into NVDA."""),
"",_(u"""Example:"""),
_(u"""> In NVDA settings ensure that:"""),
_(u"""> - Keyboard category"""),
_(u""">   - \"speak typed characters\" is unchecked"""),
_(u""">   - \"speak typed words\" is checked"""),
_(u""">"""),
_(u"""> 1. Open notepad"""),
_(u"""> 2. Type \"hello\""""),
_(u"""> 3. Press space"""),
_(u""">"""),
_(u"""> Expect \"hello\" to be announced."""),
"",_(u"""- If many NVDA settings are required, consider attaching a sample `nvda.ini` file to the PR."""),
_(u"""- If a complicated document is required to test with a 3rd party application, consider attaching it to the PR for others to test with."""),
"",_(u"""### Known issues with pull request:"""),
_(u"""Are there any known issues or downsides of this approach. For instance: _Will not work with python 3_"""),
"",_(u"""### Change log entry:"""),
_(u"""An entry intended to explain changes in NVDA to end users. Your proposed entry will be added to the `changes.t2t` file which is converted to html and used as a whats changed / change log document."""),
_(u"""See ([`user_docs/en/changes.t2t`](https://github.com/nvaccess/nvda/blob/master/user_docs/en/changes.t2t))"""),
"",_(u"""Because the `changes.t2t` file is prone to conflicts, we ask contributors not to edit the file directly, but instead add the entry to the bottom of the PR description."""),
_(u"""A lead developer will update file when merging the pull request."""),
"",_(u"""For instance:"""),
_(u"""```"""),
_(u"""*New features*"""),
_(u"""`Added a command to announce useful thing. (#WXYZ, #ABCD)`"""),
"",_(u"""*Changes*"""),
_(u"""`Old command, now also uses new useful command. (#WXYZ)`"""),
_(u"""```"""),
"",_(u"""These descriptions should be in the format: `\"{Description of change}. (#{issue number})\"`"""),
"",_(u"""You may suggest descriptions for multiple sections. The usual sections are:"""),
_(u""" """),
_(u"""* New features"""),
_(u"""* Changes"""),
_(u"""* Bug fixes"""),
"",_(u"""Multiple issue numbers can be included, separated by comma. If there is no issue number, you can use the PR number."""),
"",_(u"""For examples see the [changes.t2t file](https://github.com/nvaccess/nvda/blob/master/user_docs/en/changes.t2t)"""),
]