# -*- coding: utf-8 -*-
documentation = [
_(u"""# Creating PR's on the NVDA project"""),
"",_(u"""This page is meant to serve as an explanation for how to fill out [our Github pull request template](https://github.com/nvaccess/nvda/blob/master/.github/PULL_REQUEST_TEMPLATE.md)"""),
"",_(u"""## The template"""),
_(u"""At the start of the template there is a HTML comment block which points to this wiki page, it can be left in place and will not appear once the issue is saved. Feel free to delete it."""),
"",_(u"""### Link to issue number:"""),
_(u"""Please include the issue number here. This helps us to keep the information linked together. If this is a minor/trivial change an issue does not need to be created. If in doubt, please create one."""),
"",_(u"""### Summary of the issue:"""),
_(u"""A quick summary of the problem you are trying to solve."""),
"",_(u"""### Description of how this pull request fixes the issue:"""),
_(u"""Please include a quick discussion of how this change addresses the issue. Please also include any links or external information you may have used in order to address the issue. This helps others to have the same background as you and learn from this work."""),
"",_(u"""### Testing performed:"""),
_(u"""How have you tested to ensure that your change works as intended, across all supported operating systems, without introducing regressions? Please use this section as an opportunity to try to convince us (and yourself) that your proposed change should be merged. """),
"",_(u"""### Known issues with pull request:"""),
_(u"""Are there any known issues or downsides of this approach. For instance: _Will not work with python 3_"""),
"",_(u"""### Change log entry:"""),
_(u"""The section and description of this change to use for the changes file. The valid sections are:"""),
_(u""" """),
_(u"""* New features"""),
_(u"""* Changes"""),
_(u"""* Bug fixes"""),
"",_(u"""For examples see the [changes.t2t file](https://github.com/nvaccess/nvda/blob/master/user_docs/en/changes.t2t)"""),
]