# -*- coding: utf-8 -*-
documentation = [
_(u"""# Using GitHub Actions to manage NVDA add-ons """),
"",_(u"""This document is based on the [article about Appveyor](https://github.com/nvdaaddons/nvdaaddons.github.io/wiki/appveyor)."""),
"",_(u"""## Procedure to build, lint and attach nvda-addon files to releases on GitHub"""),
"",_(u"""### Setting GitHub Actions for add-ons"""),
"",_(u"""This works for add-ons based on the [Add-on Template](https://github.com/nvdaaddons/addontemplate)."""),
"",_(u"""1. Get the code of an add-on."""),
"",_(u"""	Example:"""),
"",_(u"""	```"""),
_(u"""	git clone https://github.com/username/repo"""),
"",_(u"""	git pull"""),
_(u"""	```"""),
_(u"""2. In the root of the add-on folder (where the sconstruct file is placed), paste this [Flake8 configuration file](https://gist.githubusercontent.com/nvdaes/9caffa59ebbdcfd3e69f8a200b512be9/raw/3cbaaff48239b1b98e863901cf6a76b955412df7/setup.cfg), which uses [Flake8 rules configured for NVDA](https://raw.githubusercontent.com/nvaccess/nvda/master/tests/lint/flake8.ini). This must be named setup.cfg"""),
"",_(u"""3. Under the root folder of the add-on repository, create a `.github/workflows` subdirectory."""),
"",_(u"""4. Inside the `repositoryRootFolder/.github/workflows` subfolder, you can paste this [GitHub workflow file](https://gist.githubusercontent.com/nvdaes/05451e4e6065bf67a2f121b3028de5ec/raw/5fc51f0b0bbeb807d22f5bceb7eafcec1e0911c1/addon.yml). File extension should be .yml (or .yaml)."""),
"",_(u"""- The above workflow will be triggered on push and pull request events."""),
_(u"""- Errors detected by Flake8 will be shown, but won't stop the workflow, so that the add-on can be built or released even when syntax or style errors are found."""),
"",_(u"""Here is info about [viewing and managing GitHub workflows](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run)."""),
"",_(u"""### Releasing"""),
"",_(u"""To post a new release of an add-on, you can create a tag and push it to GitHub:"""),
"",_(u"""Example"""),
"",_(u"""```"""),
_(u"""git tag 1.0"""),
"",_(u"""git push origin 1.0"""),
_(u"""```"""),
"",_(u"""Now, the release will be created and binary-1.0.nvda-addon will be attached on GitHub."""),
"",_(u"""With the provided yaml file, releases created from tags ending with \"-dev\" will be marked as prereleases."""),
"",_(u"""Example"""),
"",_(u"""```"""),
_(u"""git tag 1.0-dev"""),
"",_(u"""git push origin 1.0-dev"""),
_(u"""```"""),
"",_(u"""## References"""),
"",_(u"""### Documentation"""),
"",_(u"""- [GitHub Actions documentation](https://help.github.com/en/actions)"""),
_(u"""- [Flake8 documentation](https://flake8.pycqa.org/en/latest/)"""),
"",_(u"""### Used actions"""),
"",_(u"""- [actions/checkout: Action for checking out a repo](https://github.com/actions/checkout)"""),
_(u"""- [actions/create-release: An Action to create releases via the GitHub Release API](https://github.com/actions/create-release)"""),
_(u"""- [svenstaro/upload-release-action: Upload files to a GitHub release](https://github.com/svenstaro/upload-release-action)"""),
"",_(u"""### Real example"""),
"",_(u"""- [clipContentsDesigner NVDA add-on](https://github.com/nvdaes/clipContentsDesigner)"""),
]