# -*- coding: utf-8 -*-
documentation = [
_(u"""# Release Process"""),
"",_(u"""This document provides rough guidelines for the process of developing NVDA releases. All current and potential developers and translators should read and follow this document. These guidelines may be broken under special circumstances. Any concerns should be discussed with the lead developers: Mick Curran (@michaelDCurran) and Reef Turner (@feerrenrut)."""),
_(u""" """),
_(u"""## Release Workflow"""),
_(u"""This is the general release workflow. Information for specific community groups is provided in later sections. The production of a release consists of the following:"""),
_(u"""1. Development Phase"""),
_(u"""   - Development is done in parallel to the release process for the prior version. E.G. NVDA 2020.2 is in development while NVDA 2020.1 is going through the Release Phase"""),
_(u"""1. Release Phase"""),
_(u"""   - Final testing, and translations work prior to release."""),
"",_(u"""### Development phase"""),
_(u"""* Contributions are made according to the [For Developers](#for-developers) section """),
_(u"""* Once a pull request has been reviewed and approved by at least one NVDA Collaborator and all build checks have passed, a lead developer will make a final commit to the pull request which updates `changes.t2t`, and then will squash merge the pull request into master."""),
_(u"""* If the merging of a pull request to `master` causes any build checks on `master` to fail, the pull request is reverted without question. This is however unlikely to be an issue as build checks on the pull request itself must have already passed."""),
_(u"""* If a merged pull request has been identified as causing a regression, new bug, or does not work as originally reported, the pull request may be reverted at the discretion of the lead developers. Reasons in favor of not reverting the pull request may be: """),
_(u"""  * The pull request was submitted by an active collaborator who is likely to follow up with a suitable pull request to address the issues."""),
_(u"""  * The bug is trivial enough to be fixed by a collaborator."""),
_(u"""*  Automatic 'alpha snapshots' are made available to the public for very early testing. See [For Testers](#for-testers)"""),
"",_(u"""### Release phase"""),
_(u"""The release phase is intended to refine the release, with testing from wider audiences, and incorporated translations."""),
_(u"""When no blocking issues are encountered it is expected to take 7 weeks:"""),
_(u"""- Beta builds: 6 weeks (starting 7 weeks before release)"""),
_(u"""  - 4 weeks to receive any required fixes"""),
_(u"""  - 2 weeks for translation freeze (starting 3 weeks before release) """),
_(u"""- RC: 1 week."""),
_(u"""  - When issues are encountered, subsequent RC's may take another week at the discretion of lead developers."""),
"",_(u"""#### Beta builds"""),
_(u"""* A commit without any known serious issues, will be selected from the 'master' branch and merged into 'beta', this draws the line for features included in the release."""),
_(u"""  - This commit will have been on `master` and thus, in 'alpha builds' for at least 2 weeks and can now be considered beta quality."""),
_(u"""* A tagged 'beta release' will be created for wider testing. """),
_(u"""* New pull requests may be now considered for squash merging straight to beta."""),
_(u"""  - If addressing regression introduced in this release."""),
_(u"""  - If addressing a bug in a \"must have\" feature for this release."""),
_(u"""  - If addressing a critical Operating System change out of our control."""),
_(u"""* As appropriate new tagged beta releases will be published. """),
_(u"""* As necessary `beta` will be merged back into master."""),
_(u"""  - For critical pull requests or translation merges."""),
_(u"""* If a merged pull request that reached beta has been identified as causing a regression, new bug, or does not work as originally reported:"""),
_(u"""  - The pull request may be reverted at the discretion of the lead developers."""),
_(u"""  - It may be fixed by a collaborator if the bug is trivial enough."""),
_(u"""  - Once a PR is reverted from `beta`, a replacement PR is very unlikely to get into the current release."""),
"",_(u"""### Translatable String Freeze"""),
_(u"""- The beta branch will enter a translatable string freeze."""),
_(u"""- No changes to text strings that affect translations are allowed. Minor spelling or grammatical fixes may be made to documentation files, but `gettext` strings in the code should not be changed at all."""),
_(u"""* Only critical bug fixes and translation updates should be committed to the beta branch at this stage. Otherwise the translation period will need to be extended by an appropriate amount of time."""),
"",_(u"""### Release Candidate"""),
_(u"""* After the translatable string freeze, the \"rc\" branch will be created based on the beta branch."""),
_(u"""* The first release candidate will immediately be released from the `rc` branch."""),
_(u"""* After this, only critical bug fixes should be committed to the `rc` branch."""),
_(u"""* Subsequent release candidates may be released."""),
_(u"""* The final release can only be made if there have been no significant changes and at least 1 week since the last release candidate."""),
"",_(u"""### Representation on GitHub"""),
_(u"""* For most items, an issue will be filed and discussed before a pull request is submitted."""),
_(u"""* If priority should be given to an issue for inclusion in a specific release, its milestone should be set to the appropriate release milestone (e.g. 2014.4)."""),
_(u"""* Once a pull request is squash merged to the master branch, the milestone for the issue (if any) and pull request should be set to the next release milestone (e.g. 2013.2) and it should be closed as fixed."""),
_(u"""* Issues/pull requests for bug fixes for an rc should have their milestone set to the relevant release (e.g. 2013.2)."""),
"",_(u"""### Scheduled Releases"""),
_(u"""* In the past NVDA has been released 4 times per year. This is not expected to change drastically. The exact date for each release will be determined by the lead developers."""),
"",_(u"""### Maintenance Release"""),
_(u"""* Under rare circumstances, a maintenance release (e.g. 2013.1.1) may be made."""),
_(u"""* A maintenance release may only include fixes for crashes and major security issues."""),
_(u"""* Maintenance releases are made from the `rc` branch."""),
"",_(u"""## For Developers"""),
_(u"""* GitHub issues should be created for most issues and discussed prior to starting work or submitting a pull request. This is to give lead developers and the community a chance to give feedback on the approach and prevent disappointment or wasted effort for contributors. However, some trivial changes might not require an issue first. See [[Contributing]] for details."""),
_(u"""* Work should be done in topic branches. Including for external contributors."""),
_(u"""  - A PR attempting to merge in the master branch of a contributors fork may not get automatic Pull Request builds."""),
_(u"""* Any relevant documentation should be included in the topic branch."""),
_(u"""* The topic branch should be submitted for inclusion using a pull request."""),
_(u"""* New commands, drivers, settings, dialogs, etc. must be documented in the User Guide as appropriate."""),
_(u"""* All Pull Requests must follow the Pull Request template provided."""),
_(u"""* Pull requests must be based on NVDA's master branch."""),
_(u"""  - A lead developer may specifically requested the pull request be made against `beta` or `rc` in the case of addressing bugs introduced in the current release cycle."""),
_(u"""* Submitted pull requests should not contain edits to `changes.t2t."""),
_(u"""  - Instead, change log entries should be placed in the pull request description, under the appropriate section in the template."""),
_(u"""* All pull requests submitted must have their \"Allow edits from maintainers\" checkbox ticked. This is the GitHub default for new pull requests."""),
"",_(u"""## For Translators"""),
_(u"""* All translation should be based on the `beta` branch."""),
_(u"""* Translators should ensure their translation is up to date a day before the translatable string freeze ends in order for it to be included in the upcoming final release. The lead developers will announce the deadline when the freeze begins, if in doubt check the [NVDA-Translations message board](https://groups.io/g/nvda-translations/) for the \"language freeze\" announcement. Work submitted after this time will not be included in the upcoming release."""),
"",_(u"""## For Testers"""),
_(u"""* Pre-release builds for testing (known as \"snapshot builds\") can be downloaded from the snapshots page at https://www.nvaccess.org/files/nvda/snapshots/."""),
_(u"""  - It lists 'alpha snapshots', 'beta releases', and 'release candidates'. """),
_(u"""* The `alpha` builds are bleeding edge. It includes code that is being tested for possible inclusion in upcoming releases, but it may not yet be tested much (if at all) and there may be major bugs. Alpha snapshots are created directly from the `master` branch each time it changes (I.E. when a pull request is merged). Although the automated tests pass, these builds have likely had no user testing."""),
_(u"""* 'beta releases' are 'beta' quality. They include all features for the upcoming release that have proved stable in the alpha builds. A feature is considered stable if it has been in 'alpha builds' for at least a week."""),
_(u"""* 'rc releases' in most cases will be identical to the final release."""),
]